# Metadata for your course

title: OL Course
tagline: OL Steps to PR
description: Lets Go from 0 to PR 1 in less than 10 minutes with this course.

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: vcr-ol-lab-repo
  repo: lab-starter-template

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: createIssue
  title: Welcome
  body: welcome-text.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title:  The Step Title        # the title of the step, shown to the learner in the course progress page
  description: The Step descripton   # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  event:          # a list of the actions that will occur when the step is triggered by an event
  actions:
  - type:         # the type of action, full list at https://lab.github.com/docs/actions
                  # some actions require additional options, those should appear below `type:`
                  # you can execute multiple actions in the `before` block
                  #
  # - type:
  #   option:
  #
  # - type:
  #   option:
